# 计算奇异值

给一个调库的实现，然后本打算改了一下那篇CSDN的手工实现，发现那篇CSDN一样也是在调库，就没再改了。

In [5]:
import numpy as np

# 定义一个矩阵
A = np.array([[1, 2, 0],
              [2, 0, 2],])

# 计算奇异值分解
U, S, VT = np.linalg.svd(A)

# U矩阵
print("U矩阵：")
print(U)
print()

# 奇异值矩阵
print("奇异值矩阵：")
print(np.diag(S))
print()

# V转置矩阵
print("V转置矩阵：")
print(VT)

U矩阵：
[[ 0.4472136   0.89442719]
 [ 0.89442719 -0.4472136 ]]

奇异值矩阵：
[[3. 0.]
 [0. 2.]]

V转置矩阵：
[[ 7.45355992e-01  2.98142397e-01  5.96284794e-01]
 [-2.41286172e-16  8.94427191e-01 -4.47213595e-01]
 [-6.66666667e-01  3.33333333e-01  6.66666667e-01]]
